# --[ Boost
FIND_PACKAGE(Boost REQUIRED COMPONENTS regex)
INCLUDE_DIRECTORIES(SYSTEM ${Boost_INCLUDE_DIR})
LIST(APPEND FVERIFY_LINKER_LIBS ${Boost_LIBRARIES})

FIND_PACKAGE(Threads REQUIRED)
LIST(APPEND FVERIFY_LINKER_LIBS ${CMAKE_THREAD_LIBS_INIT})

# --[ OpenCV
FIND_PACKAGE(OpenCV REQUIRED COMPONENTS core highgui imgproc gpu)
INCLUDE_DIRECTORIES(SYSTEM ${OpenCV_INCLUDE_DIRS})
LIST(APPEND FVERIFY_LINKER_LIBS ${OpenCV_LIBS})

# ---[ Google-glog
include("cmake/external/glog.cmake")
include_directories(SYSTEM ${GLOG_INCLUDE_DIRS})
list(APPEND FVERIFY_LINKER_LIBS ${GLOG_LIBRARIES})

# ---[ Google-gflags
include("cmake/external/gflags.cmake")
include_directories(SYSTEM ${GFLAGS_INCLUDE_DIRS})
list(APPEND FVERIFY_LINKER_LIBS ${GFLAGS_LIBRARIES})

FIND_PACKAGE(CUDA REQUIRED)
INCLUDE_DIRECTORIES(SYSTEM ${CUDA_INCLUDE_DIRS})
LIST(APPEND FVERIFY_LINKER_LIBS ${CUDA_LIBRARIES} ${CUDA_CUBLAS_LIBRARIES})
